language: csharp
solution: GetPerfCountForNagios.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore GetPerfCountForNagios.sln
script:
  - xbuild /p:Configuration=Release GetPerfCountForNagios.sln
  - nunit-console ./GetPerfCountForNagios/GetPerfCountForNagios.Test/bin/Release/GetPerfCountForNagios.Test.dll
